# Generated by Django 2.2.20 on 2021-06-29 15:54

from django.db import migrations

import phonenumbers


def normalize_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for phone in Flat.objects.all():
        pure_phonenumber = phonenumbers.parse(phone.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(pure_phonenumber):
            phone.owner_pure_phone = phonenumbers.format_number(pure_phonenumber, phonenumbers.PhoneNumberFormat.E164)
            phone.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for phone in Flat.objects.all():
        phone.owner_pure_phone = ''
        phone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phonenumbers, move_backward)
    ]
