# Generated by Django 2.2.20 on 2021-06-29 16:20

from django.db import migrations


def transfer_owners_data(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            owner=flat.owner,
            defaults={
                'owners_phonenumber': flat.owners_phonenumber,
                'owner_pure_phone': flat.owner_pure_phone
            }
        )


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.owner = ''
        owner.owners_phonenumber = ''
        owner.owner_pure_phone = ''
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(transfer_owners_data, move_backward)
    ]
