# Generated by Django 2.2.20 on 2021-06-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20210629_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owned_flats',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='owned_by', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
